version: '3'
services:
    db:
        image: postgres:12.8
        environment:
            POSTGRES_PASSWORD: enviu_dev
            POSTGRES_USER: postgres
        network_mode: host
    blockscout:
        image: blockscout:test
        depends_on:
            - "db"
        ports:
            - "4000:4000"
        tty: true
        environment:
            ETHEREUM_JSONRPC_HTTP_URL: https://testnet.diora.network
            ETHEREUM_JSONRPC_TRACE_URL: https://testnet.diora.network
            ETHEREUM_JSONRPC_WS_URL: https://dev.diora.network
            DATABASE_URL: postgresql://postgres:@127.17.0.1:5432/explorer?ssl=false
